### ISSUE TITLE
RB version 6.1.0 support?

### ISSUE THREAD

**Issue by FaithInTheGlitch** [LePopal/PRACT-OBS#14]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by craigspree** [comment]
Does it not work with 6.1? I haven't upgraded from RB 6.0.3 yet as I don't want to lose PRACT-OBS functionality. I'd like to upgrade to 6.1 for the track editing functionality, however.

What happens when you try to use it with RB 6.1 @FaithInTheGlitch ? Does the program (PRACT) crash or display an error message? CC @LePopal

**Comment by LePopal** [comment]
I've tried it successfully on 6.1.0. Haven't tried 6.1.1 yet.

Le jeu. 24 sept. 2020 à 20:21, craigspree <notifications@github.com> a
écrit :
