### ISSUE TITLE
Track information updates are delayed

### ISSUE THREAD

**Issue by rorosaurus** [LePopal/PRACT-OBS#17]
Excellent tool, thank you for making this! Very clever to read the database directly to scrape the track info!

I notice that when playing a new track on rekordbox, it takes ~30 seconds, sometimes nearly 1 minute, for PRACT to notice the change. I've even tried setting the polling interval to 1 second, and I see the "last export" time is growing properly, however it takes much longer than I expected for it to recognize the new track information.

Is this expected? Is this a limitation of reading from the rekordbox database? Or an issue specific to my setup?

If there are there some debug steps, I'd be happy to dive deeper! Thank you again for this helpful tool!

**Comment by rorosaurus** [comment]
(rekordbox v6.4.2)

**Comment by LePopal** [comment]
Hi

This is not actually a bug because it's the way Rekordbox works. It waits
for 1 minute of playing time to add the track to the history playlist that
PRACT-OBS monitors.
There's is no way at this time to shorten this delay.

Popal

Le ven. 1 janv. 2021 à 22:59, Rory Hayes <notifications@github.com> a
écrit :

**Comment by rorosaurus** [comment]
Ah, I understand! Good to know this is as good as it gets!

Thank you again for this very helpful tool! 😄
